### ISSUE TITLE
Organize Discord Bot Commands into Separate Files for Better Code Management

### ISSUE THREAD

**Issue by dead-shadow-7** [GDGC-MET/DobbyBot#2]
**Is your feature request related to a problem? Please describe.**
The current bot code has all the commands written in a single file, which causes the file to grow large and difficult to maintain. This makes it harder to locate specific commands, update them, or add new features. I'm frustrated when I have to scroll through the file to manage individual commands.

**Describe the solution you'd like**
I'd like to refactor the code by separating each bot command into its own file. This would make the code more modular, organized, and easier to manage. Commands will be located in individual files within a dedicated folder, and these will be dynamically loaded when the bot starts.

**Describe alternatives you've considered**
An alternative could be to group commands by their type or functionality (e.g., message-based commands in one file, slash commands in another), but this still doesn't provide the same level of clarity and maintainability as splitting them into individual files.

**Additional context**
This change will improve code readability, maintainability, and make the bot easier to extend. Here's a sample of the current code to show how it can be split up:

Please assign this issue to me under Hacktoberfest. I would like to work on organizing the bot commands into separate files for improved code organization.

**Comment by Anshul-004** [comment]
Ok, You may proceed, just make sure you don't hamper unnecessary files.
