### ISSUE TITLE
Adding more commands to bot.

### ISSUE THREAD

**Issue by dead-shadow-7** [GDGC-MET/DobbyBot#4]
**Is your feature request related to a problem? Please describe.**
Currently, the bot has only a few basic commands, limiting its functionality. It would be great to expand its capabilities by adding more commands for users to interact with, enhancing the overall user experience.

**Describe the solution you'd like**
I would like to add several new commands to the bot, such as:

- _/joke_: Responds with a random joke.
- _/quote_: Sends a random inspirational quote.

These commands will add fun and useful interactions for users.

**Describe alternatives you've considered**
An alternative would be to create custom commands based on specific user needs or community feedback. However, starting with commonly used commands like jokes, weather, and quotes can improve engagement without overcomplicating the bot.

**Comment by Anshul-004** [comment]
you may proceed
